package sungil.furuyonideckbuilder

import android.content.Context
import android.widget.Toast
import androidx.room.Room
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import sungil.furuyonideckbuilder.data.Card
import sungil.furuyonideckbuilder.data.CardDatabase

fun insert(context: Context) {
    val db = Room.databaseBuilder(
        context.applicationContext,
        CardDatabase::class.java,
        "user-database"
    ).build()



    CoroutineScope(Dispatchers.IO).launch {
        db!!.cardDao().deleteAll()
        val check = db!!.cardDao().select("유리나")
        if (check.isEmpty()) {
            val test = arrayOf(
                Card("유리나", "http://furuyonideck.com/images/ge/1/0.png", "참", 1, false),
                Card("유리나", "http://furuyonideck.com/images/ge/1/1.png", "일섬", 2, false),
                Card("유리나", "http://furuyonideck.com/images/ge/1/2.png", "자루치기", 3, false),
                Card("유리나", "http://furuyonideck.com/images/ge/1/3.png", "거합", 4, false),
                Card("유리나", "http://furuyonideck.com/images/ge/1/4.png", "기백", 5, false),
                Card("유리나", "http://furuyonideck.com/images/ge/1/5.png", "압도", 6, false),
                Card("유리나", "http://furuyonideck.com/images/ge/1/6.png", "기염만장", 7, false),
                Card("유리나", "http://furuyonideck.com/images/bi/1/0.png", "달그림자떨어지니", 8, true),
                Card("유리나", "http://furuyonideck.com/images/bi/1/1.png", "해안에파랑일며", 9, true),
                Card("유리나", "http://furuyonideck.com/images/bi/1/2.png", "쪽배에서쉬노니", 10, true),
                Card("유리나", "http://furuyonideck.com/images/bi/1/3.png", "아마네유리나의저력", 11, true),
                Card("유리나A", "http://furuyonideck.com/images/ge/2/0.png", "난타", 1, false),
                Card("유리나A", "http://furuyonideck.com/images/ge/2/1.png", "일섬", 2, false),
                Card("유리나A", "http://furuyonideck.com/images/ge/2/2.png", "자루치기", 3, false),
                Card("유리나A", "http://furuyonideck.com/images/ge/2/3.png", "거합", 4, false),
                Card("유리나A", "http://furuyonideck.com/images/ge/2/4.png", "기백", 5, false),
                Card("유리나A", "http://furuyonideck.com/images/ge/2/5.png", "콩알탄", 6, false),
                Card("유리나A", "http://furuyonideck.com/images/ge/2/6.png", "기염만장", 7, false),
                Card("유리나A", "http://furuyonideck.com/images/bi/2/0.png", "달그림자떨어지니", 8, true),
                Card("유리나A", "http://furuyonideck.com/images/bi/2/1.png", "불완전해안엔파랑일며", 9, true),
                Card("유리나A", "http://furuyonideck.com/images/bi/2/2.png", "쪽배에서쉬노니", 10, true),
                Card("유리나A", "http://furuyonideck.com/images/bi/2/3.png", "아마네유리나의저력", 11, true),
                Card("사이네", "http://furuyonideck.com/images/ge/3/0.png", "팔방휘두르기", 1, false),
                Card("사이네", "http://furuyonideck.com/images/ge/3/1.png", "후려베기", 2, false),
                Card("사이네", "http://furuyonideck.com/images/ge/3/2.png", "무게추", 3, false),
                Card("사이네", "http://furuyonideck.com/images/ge/3/3.png", "간파", 4, false),
                Card("사이네", "http://furuyonideck.com/images/ge/3/4.png", "권역", 5, false),
                Card("사이네", "http://furuyonideck.com/images/ge/3/5.png", "충음정", 6, false),
                Card("사이네", "http://furuyonideck.com/images/ge/3/6.png", "무음벽", 7, false),
                Card("사이네", "http://furuyonideck.com/images/bi/3/0.png", "율동호극", 8, true),
                Card("사이네", "http://furuyonideck.com/images/bi/3/1.png", "항명공진", 9, true),
                Card("사이네", "http://furuyonideck.com/images/bi/3/2.png", "무음쇄빙", 10, true),
                Card("사이네", "http://furuyonideck.com/images/bi/3/3.png", "히사메사이네의최후의종극", 11, true),
                Card("사이네A", "http://furuyonideck.com/images/ge/4/0.png", "팔방휘두르기", 1, false),
                Card("사이네A", "http://furuyonideck.com/images/ge/4/1.png", "후려베기", 2, false),
                Card("사이네A", "http://furuyonideck.com/images/ge/4/2.png", "얼음의소리", 3, false),
                Card("사이네A", "http://furuyonideck.com/images/ge/4/3.png", "간파", 4, false),
                Card("사이네A", "http://furuyonideck.com/images/ge/4/4.png", "권역", 5, false),
                Card("사이네A", "http://furuyonideck.com/images/ge/4/5.png", "반주", 6, false),
                Card("사이네A", "http://furuyonideck.com/images/ge/4/6.png", "무음벽", 7, false),
                Card("사이네A", "http://furuyonideck.com/images/bi/4/0.png", "율동호극", 8, true),
                Card("사이네A", "http://furuyonideck.com/images/bi/4/1.png", "이중주:탄주빙명", 9, true),
                Card("사이네A", "http://furuyonideck.com/images/bi/4/2.png", "무음쇄빙", 10, true),
                Card("사이네A", "http://furuyonideck.com/images/bi/4/3.png", "히사메사이네의최후의종극", 11, true),
                Card("사이네A2", "http://furuyonideck.com/images/ge/5/0.png", "팔방휘두르기", 1, false),
                Card("사이네A2", "http://furuyonideck.com/images/ge/5/1.png", "등배기", 2, false),
                Card("사이네A2", "http://furuyonideck.com/images/ge/5/2.png", "무게추", 3, false),
                Card("사이네A2", "http://furuyonideck.com/images/ge/5/3.png", "간파", 4, false),
                Card("사이네A2", "http://furuyonideck.com/images/ge/5/4.png", "권역", 5, false),
                Card("사이네A2", "http://furuyonideck.com/images/ge/5/5.png", "충음정", 6, false),
                Card("사이네A2", "http://furuyonideck.com/images/ge/5/6.png", "유향벽", 7, false),
                Card("사이네A2", "http://furuyonideck.com/images/bi/5/0.png", "율동호극", 8, true),
                Card("사이네A2", "http://furuyonideck.com/images/bi/5/1.png", "항명공진", 9, true),
                Card("사이네A2", "http://furuyonideck.com/images/bi/5/2.png", "절창절화", 10, true),
                Card(
                    "사이네A2",
                    "http://furuyonideck.com/images/bi/5/3.png",
                    "히사메사이네의최후의종극",
                    11,
                    true
                ),
                Card("히미카", "http://furuyonideck.com/images/ge/6/0.png", "슛", 1, false),
                Card("히미카", "http://furuyonideck.com/images/ge/6/1.png", "래피드파이어", 2, false),
                Card("히미카", "http://furuyonideck.com/images/ge/6/2.png", "매그넘캐논", 3, false),
                Card("히미카", "http://furuyonideck.com/images/ge/6/3.png", "풀버스트", 4, false),
                Card("히미카", "http://furuyonideck.com/images/ge/6/4.png", "백스탭", 5, false),
                Card("히미카", "http://furuyonideck.com/images/ge/6/5.png", "백드래프트", 6, false),
                Card("히미카", "http://furuyonideck.com/images/ge/6/6.png", "스모크", 7, false),
                Card("히미카", "http://furuyonideck.com/images/bi/6/0.png", "레드불릿", 8, true),
                Card("히미카", "http://furuyonideck.com/images/bi/6/1.png", "크림슨제로", 9, true),
                Card("히미카", "http://furuyonideck.com/images/bi/6/2.png", "스칼렛이매진", 10, true),
                Card("히미카", "http://furuyonideck.com/images/bi/6/3.png", "버밀리온필드", 11, true),
                Card("히미카A", "http://furuyonideck.com/images/ge/7/0.png", "슛", 1, false),
                Card("히미카A", "http://furuyonideck.com/images/ge/7/1.png", "화염류", 2, false),
                Card("히미카A", "http://furuyonideck.com/images/ge/7/2.png", "매그넘캐논", 3, false),
                Card("히미카A", "http://furuyonideck.com/images/ge/7/3.png", "풀버스트", 4, false),
                Card("히미카A", "http://furuyonideck.com/images/ge/7/4.png", "살의", 5, false),
                Card("히미카A", "http://furuyonideck.com/images/ge/7/5.png", "백드래프트", 6, false),
                Card("히미카A", "http://furuyonideck.com/images/ge/7/6.png", "스모크", 7, false),
                Card("히미카A", "http://furuyonideck.com/images/bi/7/0.png", "레드불릿", 8, true),
                Card("히미카A", "http://furuyonideck.com/images/bi/7/1.png", "염천쿠레나이히미카", 9, true),
                Card("히미카A", "http://furuyonideck.com/images/bi/7/2.png", "스칼렛이매진", 10, true),
                Card("히미카A", "http://furuyonideck.com/images/bi/7/3.png", "버밀리온필드", 11, true),
                Card("토코요", "http://furuyonideck.com/images/ge/8/0.png", "빗어내리기", 1, false),
                Card("토코요", "http://furuyonideck.com/images/ge/8/1.png", "우아한타격", 2, false),
                Card("토코요", "http://furuyonideck.com/images/ge/8/2.png", "날뛰는토끼", 3, false),
                Card("토코요", "http://furuyonideck.com/images/ge/8/3.png", "시의춤", 4, false),
                Card("토코요", "http://furuyonideck.com/images/ge/8/4.png", "부채뒤집기", 5, false),
                Card("토코요", "http://furuyonideck.com/images/ge/8/5.png", "바람의무대", 6, false),
                Card("토코요", "http://furuyonideck.com/images/ge/8/6.png", "맑음의무대", 7, false),
                Card("토코요", "http://furuyonideck.com/images/bi/8/0.png", "영원의꽃", 8, true),
                Card("토코요", "http://furuyonideck.com/images/bi/8/1.png", "천년의새", 9, true),
                Card("토코요", "http://furuyonideck.com/images/bi/8/2.png", "무궁의바람", 10, true),
                Card("토코요", "http://furuyonideck.com/images/bi/8/3.png", "상세의달", 11, true),
                Card("토코요A", "http://furuyonideck.com/images/ge/9/0.png", "흐르는연주", 1, false),
                Card("토코요A", "http://furuyonideck.com/images/ge/9/1.png", "우아한타격", 2, false),
                Card("토코요A", "http://furuyonideck.com/images/ge/9/2.png", "날뛰는토끼", 3, false),
                Card("토코요A", "http://furuyonideck.com/images/ge/9/3.png", "시의춤", 4, false),
                Card("토코요A", "http://furuyonideck.com/images/ge/9/4.png", "햇볕의소리", 5, false),
                Card("토코요A", "http://furuyonideck.com/images/ge/9/5.png", "바람의무대", 6, false),
                Card("토코요A", "http://furuyonideck.com/images/ge/9/6.png", "맑음의", 7, false),
                Card("토코요A", "http://furuyonideck.com/images/ge/9/7.png", "무대", 8, false),
                Card("토코요A", "http://furuyonideck.com/images/bi/9/0.png", "영원의꽃", 9, true),
                Card("토코요A", "http://furuyonideck.com/images/bi/9/1.png", "이중주:취탄양명", 10, true),
                Card("토코요A", "http://furuyonideck.com/images/bi/9/2.png", "무궁의바람", 11, true),
                Card("토코요A", "http://furuyonideck.com/images/bi/9/3.png", "상세의달", 12, true),
                Card("토코요A2", "http://furuyonideck.com/images/ge/10/0.png", "빗어내리기", 1, false),
                Card("토코요A2", "http://furuyonideck.com/images/ge/10/1.png", "두려움스치기", 2, false),
                Card("토코요A2", "http://furuyonideck.com/images/ge/10/2.png", "날뛰는토끼", 3, false),
                Card("토코요A2", "http://furuyonideck.com/images/ge/10/3.png", "시의춤", 4, false),
                Card("토코요A2", "http://furuyonideck.com/images/ge/10/4.png", "부채뒤집기", 5, false),
                Card("토코요A2", "http://furuyonideck.com/images/ge/10/5.png", "바람의무대", 6, false),
                Card("토코요A2", "http://furuyonideck.com/images/ge/10/6.png", "맑음의무대", 7, false),
                Card("토코요A2", "http://furuyonideck.com/images/bi/10/0.png", "영원의꽃", 8, true),
                Card("토코요A2", "http://furuyonideck.com/images/bi/10/1.png", "유구의눈", 9, true),
                Card("토코요A2", "http://furuyonideck.com/images/bi/10/2.png", "덧없이지는여덟겹벛꽃", 10, true),
                Card("토코요A2", "http://furuyonideck.com/images/bi/10/3.png", "상세의달", 11, false),
                Card("오보로", "http://furuyonideck.com/images/ge/11/0.png", "철사", 1, false),
                Card("오보로", "http://furuyonideck.com/images/ge/11/1.png", "그림자마름", 2, false),
                Card("오보로", "http://furuyonideck.com/images/ge/11/2.png", "참격난무", 3, false),
                Card("오보로", "http://furuyonideck.com/images/ge/11/3.png", "닌자걸음", 4, false),
                Card("오보로", "http://furuyonideck.com/images/ge/11/4.png", "유도", 5, false),
                Card("오보로", "http://furuyonideck.com/images/ge/11/5.png", "분신술", 6, false),
                Card("오보로", "http://furuyonideck.com/images/ge/11/6.png", "생체활성", 7, false),
                Card("오보로", "http://furuyonideck.com/images/bi/11/0.png", "쿠마스케", 8, true),
                Card("오보로", "http://furuyonideck.com/images/bi/11/1.png", "토비카게", 9, true),
                Card("오보로", "http://furuyonideck.com/images/bi/11/2.png", "우로우오", 10, true),
                Card("오보로", "http://furuyonideck.com/images/bi/11/3.png", "미카즈라", 11, true),
                Card("오보로A", "http://furuyonideck.com/images/ge/12/0.png", "철사", 1, false),
                Card("오보로A", "http://furuyonideck.com/images/ge/12/1.png", "수리검", 2, false),
                Card("오보로A", "http://furuyonideck.com/images/ge/12/2.png", "참격난무", 3, false),
                Card("오보로A", "http://furuyonideck.com/images/ge/12/3.png", "닌자걸음", 4, false),
                Card("오보로A", "http://furuyonideck.com/images/ge/12/4.png", "유도", 5, false),
                Card("오보로A", "http://furuyonideck.com/images/ge/12/5.png", "분신술", 6, false),
                Card("오보로A", "http://furuyonideck.com/images/ge/12/6.png", "생체활성", 7, false),
                Card("오보로A", "http://furuyonideck.com/images/bi/12/0.png", "쿠마스케", 8, true),
                Card("오보로A", "http://furuyonideck.com/images/bi/12/1.png", "토비카게", 9, true),
                Card("오보로A", "http://furuyonideck.com/images/bi/12/2.png", "우로우오", 10, true),
                Card("오보로A", "http://furuyonideck.com/images/bi/12/3.png", "신대의가지", 11, true),
                Card("유키히", "http://furuyonideck.com/images/ge/13/0.png", "숨긴바늘/머금은바늘", 1, false),
                Card("유키히", "http://furuyonideck.com/images/ge/13/1.png", "숨긴불꽃/손뼉치기", 2, false),
                Card("유키히", "http://furuyonideck.com/images/ge/13/2.png", "떨쳐내기/끌어당기기", 3, false),
                Card("유키히", "http://furuyonideck.com/images/ge/13/3.png", "휘두르기/푹찌르기", 4, false),
                Card("유키히", "http://furuyonideck.com/images/ge/13/4.png", "우산돌리기", 5, false),
                Card("유키히", "http://furuyonideck.com/images/ge/13/5.png", "뒷걸음질/파고들기", 6, false),
                Card("유키히", "http://furuyonideck.com/images/ge/13/6.png", "인연맺기", 7, false),
                Card("유키히", "http://furuyonideck.com/images/bi/13/0.png", "흩날리는눈꽃", 8, true),
                Card("유키히", "http://furuyonideck.com/images/bi/13/1.png", "일렁이는불꽃", 9, true),
                Card("유키히", "http://furuyonideck.com/images/bi/13/2.png", "질척이는속내", 10, true),
                Card("유키히", "http://furuyonideck.com/images/bi/13/3.png", "빙글도는몸짓", 11, true),
                Card("유키히A", "http://furuyonideck.com/images/ge/14/0.png", "숨긴바늘/머금은바늘", 1, false),
                Card("유키히A", "http://furuyonideck.com/images/ge/14/1.png", "조력하기/위협하기", 2, false),
                Card("유키히A", "http://furuyonideck.com/images/ge/14/2.png", "떨쳐내기/끌어당기기", 3, false),
                Card("유키히A", "http://furuyonideck.com/images/ge/14/3.png", "씨실/날실", 4, false),
                Card("유키히A", "http://furuyonideck.com/images/ge/14/4.png", "우산돌리기", 5, false),
                Card("유키히A", "http://furuyonideck.com/images/ge/14/5.png", "뒷걸음질/파고들기", 6, false),
                Card("유키히A", "http://furuyonideck.com/images/ge/14/6.png", "인연맺기", 7, false),
                Card("유키히A", "http://furuyonideck.com/images/bi/14/0.png", "흩날리는눈꽃", 8, true),
                Card("유키히A", "http://furuyonideck.com/images/bi/14/1.png", "살랑이는옷깃", 9, true),
                Card("유키히A", "http://furuyonideck.com/images/bi/14/2.png", "질척이는속내", 10, true),
                Card("유키히A", "http://furuyonideck.com/images/bi/14/3.png", "빙글도는몸짓", 11, true),
                Card("신라", "http://furuyonideck.com/images/ge/15/0.png", "입론", 1, false),
                Card("신라", "http://furuyonideck.com/images/ge/15/1.png", "반론", 2, false),
                Card("신라", "http://furuyonideck.com/images/ge/15/2.png", "궤변", 3, false),
                Card("신라", "http://furuyonideck.com/images/ge/15/3.png", "인용", 4, false),
                Card("신라", "http://furuyonideck.com/images/ge/15/4.png", "선동", 5, false),
                Card("신라", "http://furuyonideck.com/images/ge/15/5.png", "장담", 6, false),
                Card("신라", "http://furuyonideck.com/images/ge/15/6.png", "논파", 7, false),
                Card("신라", "http://furuyonideck.com/images/bi/15/0.png", "완전논파", 8, true),
                Card("신라", "http://furuyonideck.com/images/bi/15/1.png", "일절이해", 9, true),
                Card("신라", "http://furuyonideck.com/images/bi/15/2.png", "천지반박", 10, true),
                Card("신라", "http://furuyonideck.com/images/bi/15/3.png", "신라판증", 11, true),
                Card("신라A", "http://furuyonideck.com/images/ge/16/0.png", "입론", 1, false),
                Card("신라A", "http://furuyonideck.com/images/ge/16/1.png", "진언", 2, false),
                Card("신라A", "http://furuyonideck.com/images/ge/16/2.png", "궤변", 3, false),
                Card("신라A", "http://furuyonideck.com/images/ge/16/3.png", "인용", 4, false),
                Card("신라A", "http://furuyonideck.com/images/ge/16/4.png", "선동", 5, false),
                Card("신라A", "http://furuyonideck.com/images/ge/16/5.png", "사도", 6, false),
                Card("신라A", "http://furuyonideck.com/images/ge/16/6.png", "논파", 7, false),
                Card("신라A", "http://furuyonideck.com/images/bi/16/0.png", "완전논파", 8, true),
                Card("신라A", "http://furuyonideck.com/images/bi/16/1.png", "일절이해", 9, true),
                Card("신라A", "http://furuyonideck.com/images/bi/16/2.png", "전지경전", 10, true),
                Card("신라A", "http://furuyonideck.com/images/bi/16/3.png", "신라판증", 11, true),
                Card("하가네", "http://furuyonideck.com/images/ge/17/0.png", "원심격", 1, false),
                Card("하가네", "http://furuyonideck.com/images/ge/17/1.png", "사풍진", 2, false),
                Card("하가네", "http://furuyonideck.com/images/ge/17/2.png", "대지부수기", 3, false),
                Card("하가네", "http://furuyonideck.com/images/ge/17/3.png", "초반동", 4, false),
                Card("하가네", "http://furuyonideck.com/images/ge/17/4.png", "원무련", 5, false),
                Card("하가네", "http://furuyonideck.com/images/ge/17/5.png", "종울리기", 6, false),
                Card("하가네", "http://furuyonideck.com/images/ge/17/6.png", "인력장", 7, false),
                Card("하가네", "http://furuyonideck.com/images/bi/17/0.png", "대천공크래쉬", 8, true),
                Card("하가네", "http://furuyonideck.com/images/bi/17/1.png", "대파종메갈로벨", 9, true),
                Card("하가네", "http://furuyonideck.com/images/bi/17/2.png", "대중력어트랙트", 10, true),
                Card("하가네", "http://furuyonideck.com/images/bi/17/3.png", "대산맥리스펙트", 11, true),
                Card("하가네A", "http://furuyonideck.com/images/ge/18/0.png", "화롯불", 1, false),
                Card("하가네A", "http://furuyonideck.com/images/ge/18/1.png", "선회기", 2, false),
                Card("하가네A", "http://furuyonideck.com/images/ge/18/2.png", "대지부수기", 3, false),
                Card("하가네A", "http://furuyonideck.com/images/ge/18/3.png", "초반동", 4, false),
                Card("하가네A", "http://furuyonideck.com/images/ge/18/4.png", "원무련", 5, false),
                Card("하가네A", "http://furuyonideck.com/images/ge/18/5.png", "종울리기", 6, false),
                Card("하가네A", "http://furuyonideck.com/images/ge/18/6.png", "인력장", 7, false),
                Card("하가네A", "http://furuyonideck.com/images/bi/18/0.png", "대연성마테리얼", 8, true),
                Card("하가네A", "http://furuyonideck.com/images/bi/18/1.png", "대파종메갈로벨", 9, true),
                Card("하가네A", "http://furuyonideck.com/images/bi/18/2.png", "대중력어트랙트", 10, true),
                Card("하가네A", "http://furuyonideck.com/images/bi/18/3.png", "대산맥리스펙트", 11, true),
                Card("치카게", "http://furuyonideck.com/images/ge/19/0.png", "쿠나이던지기", 1, false),
                Card("치카게", "http://furuyonideck.com/images/ge/19/1.png", "독침", 2, false),
                Card("치카게", "http://furuyonideck.com/images/ge/19/2.png", "둔갑", 3, false),
                Card("치카게", "http://furuyonideck.com/images/ge/19/3.png", "목베기", 4, false),
                Card("치카게", "http://furuyonideck.com/images/ge/19/4.png", "독안개", 5, false),
                Card("치카게", "http://furuyonideck.com/images/ge/19/5.png", "까치발걸음", 6, false),
                Card("치카게", "http://furuyonideck.com/images/ge/19/6.png", "진흙탕", 7, false),
                Card("치카게", "http://furuyonideck.com/images/bi/19/0.png", "멸등의영혼독", 8, true),
                Card("치카게", "http://furuyonideck.com/images/bi/19/1.png", "반기에얽힌독", 9, true),
                Card("치카게", "http://furuyonideck.com/images/bi/19/2.png", "윤회의안개독", 10, true),
                Card("치카게", "http://furuyonideck.com/images/bi/19/3.png", "야미쿠라치카게의사는길", 11, true),
                Card("치카게A", "http://furuyonideck.com/images/ge/20/0.png", "쿠나이던지기", 1, false),
                Card("치카게A", "http://furuyonideck.com/images/ge/20/1.png", "독침", 2, false),
                Card("치카게A", "http://furuyonideck.com/images/ge/20/2.png", "둔갑", 3, false),
                Card("치카게A", "http://furuyonideck.com/images/ge/20/3.png", "목베기", 4, false),
                Card("치카게A", "http://furuyonideck.com/images/ge/20/4.png", "속임수우산", 5, false),
                Card("치카게A", "http://furuyonideck.com/images/ge/20/5.png", "분투", 6, false),
                Card("치카게A", "http://furuyonideck.com/images/ge/20/6.png", "진흙탕", 7, false),
                Card("치카게A", "http://furuyonideck.com/images/bi/20/0.png", "멸등의영혼독", 8, true),
                Card("치카게A", "http://furuyonideck.com/images/bi/20/1.png", "반기에얽힌독", 9, true),
                Card("치카게A", "http://furuyonideck.com/images/bi/20/2.png", "윤회의안개독", 10, true),
                Card("치카게A", "http://furuyonideck.com/images/bi/20/3.png", "잔재의인연독", 11, true),
                Card("쿠루루", "http://furuyonideck.com/images/ge/21/0.png", "엘레키텔", 1, false),
                Card("쿠루루", "http://furuyonideck.com/images/ge/21/1.png", "액셀러", 2, false),
                Card("쿠루루", "http://furuyonideck.com/images/ge/21/2.png", "쿠루룽", 3, false),
                Card("쿠루루", "http://furuyonideck.com/images/ge/21/3.png", "토네이도", 4, false),
                Card("쿠루루", "http://furuyonideck.com/images/ge/21/4.png", "리게이너", 5, false),
                Card("쿠루루", "http://furuyonideck.com/images/ge/21/5.png", "모듀르", 6, false),
                Card("쿠루루", "http://furuyonideck.com/images/ge/21/6.png", "리플렉터", 7, false),
                Card("쿠루루", "http://furuyonideck.com/images/bi/21/0.png", "드레인데빌", 8, true),
                Card("쿠루루", "http://furuyonideck.com/images/bi/21/1.png", "빅골렘", 9, true),
                Card("쿠루루", "http://furuyonideck.com/images/bi/21/2.png", "인더스트리아", 10, true),
                Card("쿠루루", "http://furuyonideck.com/images/bi/21/3.png", "신섭장치쿠루루식", 11, true),
                Card("쿠루루A", "http://furuyonideck.com/images/ge/22/0.png", "애널라이즈", 1, false),
                Card("쿠루루A", "http://furuyonideck.com/images/ge/22/1.png", "엑셀러", 2, false),
                Card("쿠루루A", "http://furuyonideck.com/images/ge/22/2.png", "다우징", 3, false),
                Card("쿠루루A", "http://furuyonideck.com/images/ge/22/3.png", "토네이도", 4, false),
                Card("쿠루루A", "http://furuyonideck.com/images/ge/22/4.png", "리게이너", 5, false),
                Card("쿠루루A", "http://furuyonideck.com/images/ge/22/5.png", "모듀르", 6, false),
                Card("쿠루루A", "http://furuyonideck.com/images/ge/22/6.png", "리플렉터", 7, false),
                Card("쿠루루A", "http://furuyonideck.com/images/bi/22/0.png", "드레인데빌", 8, true),
                Card("쿠루루A", "http://furuyonideck.com/images/bi/22/1.png", "빅골렘", 9, true),
                Card("쿠루루A", "http://furuyonideck.com/images/bi/22/2.png", "라스트리서치", 10, true),
                Card("쿠루루A", "http://furuyonideck.com/images/bi/22/3.png", "신섭장치쿠루루식", 11, true),
                Card("탈리야", "http://furuyonideck.com/images/ge/23/0.png", "BurningSteam", 1, false),
                Card("탈리야", "http://furuyonideck.com/images/ge/23/1.png", "WavingEdge", 2, false),
                Card("탈리야", "http://furuyonideck.com/images/ge/23/2.png", "ShieldCharge", 3, false),
                Card("탈리야", "http://furuyonideck.com/images/ge/23/3.png", "SteamCannon", 4, false),
                Card("탈리야", "http://furuyonideck.com/images/ge/23/4.png", "Stunt", 5, false),
                Card("탈리야", "http://furuyonideck.com/images/ge/23/5.png", "Roaring", 6, false),
                Card("탈리야", "http://furuyonideck.com/images/ge/23/6.png", "TurboSwitch", 7, false),
                Card("탈리야", "http://furuyonideck.com/images/bi/23/0.png", "AlphaEdge", 8, true),
                Card("탈리야", "http://furuyonideck.com/images/bi/23/1.png", "OmegaBurst", 9, true),
                Card(
                    "탈리야",
                    "http://furuyonideck.com/images/bi/23/2.png",
                    "ThallyasMasterpiece",
                    10,
                    true
                ),
                Card(
                    "탈리야",
                    "http://furuyonideck.com/images/bi/23/3.png",
                    "JuliasBlackBox",
                    11,
                    true
                ),
                Card(
                    "탈리야A",
                    "http://furuyonideck.com/images/ge/24/0.png",
                    "BurningSteam",
                    1,
                    false
                ),
                Card("탈리야A", "http://furuyonideck.com/images/ge/24/1.png", "WavingEdge", 2, false),
                Card(
                    "탈리야A",
                    "http://furuyonideck.com/images/ge/24/2.png",
                    "ShieldCharge",
                    3,
                    false
                ),
                Card("탈리야A", "http://furuyonideck.com/images/ge/24/3.png", "SteamCannon", 4, false),
                Card("탈리야A", "http://furuyonideck.com/images/ge/24/4.png", "QuickChange", 5, false),
                Card("탈리야A", "http://furuyonideck.com/images/ge/24/5.png", "Roaring", 6, false),
                Card("탈리야A", "http://furuyonideck.com/images/ge/24/6.png", "TurboSwitch", 7, false),
                Card("탈리야A", "http://furuyonideck.com/images/bi/24/0.png", "BlackBoxNEO", 8, true),
                Card("탈리야A", "http://furuyonideck.com/images/bi/24/1.png", "OMNISBlaster", 9, true),
                Card(
                    "탈리야A",
                    "http://furuyonideck.com/images/bi/24/2.png",
                    "ThallyasMasterpiece",
                    10,
                    true
                ),
                Card(
                    "탈리야A",
                    "http://furuyonideck.com/images/bi/24/3.png",
                    "JuliasBlackBox",
                    11,
                    true
                ),
                Card("라이라", "http://furuyonideck.com/images/ge/25/0.png", "짐승의손톱", 1, false),
                Card("라이라", "http://furuyonideck.com/images/ge/25/1.png", "풍뢰격", 2, false),
                Card("라이라", "http://furuyonideck.com/images/ge/25/2.png", "윤회의손톱", 3, false),
                Card("라이라", "http://furuyonideck.com/images/ge/25/3.png", "바람달리기", 4, false),
                Card("라이라", "http://furuyonideck.com/images/ge/25/4.png", "풍뢰의지혜", 5, false),
                Card("라이라", "http://furuyonideck.com/images/ge/25/5.png", "울부짖기", 6, false),
                Card("라이라", "http://furuyonideck.com/images/ge/25/6.png", "허공답보", 7, false),
                Card("라이라", "http://furuyonideck.com/images/bi/25/0.png", "뇌라풍신조", 8, true),
                Card("라이라", "http://furuyonideck.com/images/bi/25/1.png", "천뢰소환진", 9, true),
                Card("라이라", "http://furuyonideck.com/images/bi/25/2.png", "풍마초래공", 10, true),
                Card("라이라", "http://furuyonideck.com/images/bi/25/3.png", "원환륜회선", 11, true),
                Card("라이라A", "http://furuyonideck.com/images/ge/26/0.png", "짐승의손톱", 1, false),
                Card("라이라A", "http://furuyonideck.com/images/ge/26/1.png", "폭풍", 2, false),
                Card("라이라A", "http://furuyonideck.com/images/ge/26/2.png", "윤회의손톱", 3, false),
                Card("라이라A", "http://furuyonideck.com/images/ge/26/3.png", "바람달리기", 4, false),
                Card("라이라A", "http://furuyonideck.com/images/ge/26/4.png", "풍뢰의지혜", 5, false),
                Card("라이라A", "http://furuyonideck.com/images/ge/26/5.png", "대폭풍우", 6, false),
                Card("라이라A", "http://furuyonideck.com/images/ge/26/6.png", "허공답보", 7, false),
                Card("라이라A", "http://furuyonideck.com/images/bi/26/0.png", "뇌라풍신조", 8, true),
                Card("라이라A", "http://furuyonideck.com/images/bi/26/1.png", "천뢰소환진", 9, true),
                Card("라이라A", "http://furuyonideck.com/images/bi/26/2.png", "진풍제천의", 10, true),
                Card("라이라A", "http://furuyonideck.com/images/bi/26/3.png", "원환륜회선", 11, true),
                Card("우츠로", "http://furuyonideck.com/images/ge/27/0.png", "원월", 1, false),
                Card("우츠로", "http://furuyonideck.com/images/ge/27/1.png", "검은파동", 2, false),
                Card("우츠로", "http://furuyonideck.com/images/ge/27/2.png", "수확", 3, false),
                Card("우츠로", "http://furuyonideck.com/images/ge/27/3.png", "중압", 4, false),
                Card("우츠로", "http://furuyonideck.com/images/ge/27/4.png", "그림자날개", 5, false),
                Card("우츠로", "http://furuyonideck.com/images/ge/27/5.png", "그림자벽", 6, false),
                Card("우츠로", "http://furuyonideck.com/images/ge/27/6.png", "유회주", 7, false),
                Card("우츠로", "http://furuyonideck.com/images/bi/27/0.png", "회멸", 8, true),
                Card("우츠로", "http://furuyonideck.com/images/bi/27/1.png", "허위", 9, true),
                Card("우츠로", "http://furuyonideck.com/images/bi/27/2.png", "종말", 10, true),
                Card("우츠로", "http://furuyonideck.com/images/bi/27/3.png", "마식", 11, true),
                Card("우츠로A", "http://furuyonideck.com/images/ge/28/0.png", "원월", 1, false),
                Card("우츠로A", "http://furuyonideck.com/images/ge/28/1.png", "좀먹는먼지", 2, false),
                Card("우츠로A", "http://furuyonideck.com/images/ge/28/2.png", "수확", 3, false),
                Card("우츠로A", "http://furuyonideck.com/images/ge/28/3.png", "중압", 4, false),
                Card("우츠로A", "http://furuyonideck.com/images/ge/28/4.png", "그림자날개", 5, false),
                Card("우츠로A", "http://furuyonideck.com/images/ge/28/5.png", "그림자", 6, false),
                Card("우츠로A", "http://furuyonideck.com/images/ge/28/6.png", "유회주", 7, false),
                Card("우츠로A", "http://furuyonideck.com/images/bi/28/0.png", "잔향장치쿠루루식", 8, true),
                Card("우츠로A", "http://furuyonideck.com/images/bi/28/1.png", "허위", 9, true),
                Card("우츠로A", "http://furuyonideck.com/images/bi/28/2.png", "종말", 10, true),
                Card("우츠로A", "http://furuyonideck.com/images/bi/28/3.png", "마식", 11, true),
                Card("호노카", "http://furuyonideck.com/images/ge/29/0.png", "정령식", 1, false),
                Card("호노카", "http://furuyonideck.com/images/ge/29/1.png", "벚꽃보라", 2, false),
                Card("호노카", "http://furuyonideck.com/images/ge/29/2.png", "의기공진", 3, false),
                Card("호노카", "http://furuyonideck.com/images/ge/29/3.png", "벚꽃날개", 4, false),
                Card("호노카", "http://furuyonideck.com/images/ge/29/4.png", "벚꽃부적", 5, false),
                Card("호노카", "http://furuyonideck.com/images/ge/29/5.png", "지휘", 6, false),
                Card("호노카", "http://furuyonideck.com/images/ge/29/6.png", "꽁무니바람", 7, false),
                Card("호노카", "http://furuyonideck.com/images/bi/29/0.png", "가슴에의지를", 8, true),
                Card("호노카", "http://furuyonideck.com/images/bi/29/1.png", "이깃발의이름아래", 9, true),
                Card("호노카", "http://furuyonideck.com/images/bi/29/2.png", "사계는다시돌아온다", 10, true),
                Card("호노카", "http://furuyonideck.com/images/bi/29/3.png", "만개한꽃길에서", 11, true),
                Card("호노카A", "http://furuyonideck.com/images/ge/30/0.png", "벛꽃쌍검", 1, false),
                Card("호노카A", "http://furuyonideck.com/images/ge/30/1.png", "벚꽃보라", 2, false),
                Card("호노카A", "http://furuyonideck.com/images/ge/30/2.png", "의기공진", 3, false),
                Card("호노카A", "http://furuyonideck.com/images/ge/30/3.png", "벚꽃날개", 4, false),
                Card("호노카A", "http://furuyonideck.com/images/ge/30/4.png", "벚꽃부적", 5, false),
                Card("호노카A", "http://furuyonideck.com/images/ge/30/5.png", "지휘", 6, false),
                Card("호노카A", "http://furuyonideck.com/images/ge/30/6.png", "꽁무니바람", 7, false),
                Card("호노카A", "http://furuyonideck.com/images/bi/30/0.png", "나홀로눈이뜨여", 8, true),
                Card("호노카A", "http://furuyonideck.com/images/bi/30/1.png", "이깃발의이름아래", 9, true),
                Card("호노카A", "http://furuyonideck.com/images/bi/30/2.png", "사계는다시돌아온다", 10, true),
                Card("호노카A", "http://furuyonideck.com/images/bi/30/3.png", "만개한꽃길에서", 11, true),
                Card("코르누", "http://furuyonideck.com/images/ge/31/0.png", "눈칼날", 1, false),
                Card("코르누", "http://furuyonideck.com/images/ge/31/1.png", "선회날", 2, false),
                Card("코르누", "http://furuyonideck.com/images/ge/31/2.png", "검의춤", 3, false),
                Card("코르누", "http://furuyonideck.com/images/ge/31/3.png", "눈타기", 4, false),
                Card("코르누", "http://furuyonideck.com/images/ge/31/4.png", "절대영도", 5, false),
                Card("코르누", "http://furuyonideck.com/images/ge/31/5.png", "동상", 6, false),
                Card("코르누", "http://furuyonideck.com/images/ge/31/6.png", "서리가시덤불", 7, false),
                Card("코르누", "http://furuyonideck.com/images/bi/31/0.png", "콘루루얀페", 8, true),
                Card("코르누", "http://furuyonideck.com/images/bi/31/1.png", "레타르레라", 9, true),
                Card("코르누", "http://furuyonideck.com/images/bi/31/2.png", "우파스툼", 10, true),
                Card("코르누", "http://furuyonideck.com/images/bi/31/3.png", "포루챠르토", 11, true),
                Card("야츠하", "http://furuyonideck.com/images/ge/32/0.png", "별의손톱", 1, false),
                Card("야츠하", "http://furuyonideck.com/images/ge/32/1.png", "어둠의아가리", 2, false),
                Card("야츠하", "http://furuyonideck.com/images/ge/32/2.png", "거울의악마", 3, false),
                Card("야츠하", "http://furuyonideck.com/images/ge/32/3.png", "환영보법", 4, false),
                Card("야츠하", "http://furuyonideck.com/images/ge/32/4.png", "의지", 5, false),
                Card("야츠하", "http://furuyonideck.com/images/ge/32/5.png", "계약", 6, false),
                Card("야츠하", "http://furuyonideck.com/images/ge/32/6.png", "들러붙는꽃", 7, false),
                Card("야츠하", "http://furuyonideck.com/images/bi/32/0.png", "두잎거울의재앙신", 8, true),
                Card("야츠하", "http://furuyonideck.com/images/bi/32/1.png", "네잎거울의전래동요", 9, true),
                Card("야츠하", "http://furuyonideck.com/images/bi/32/2.png", "여섯잎거울의별바다", 10, true),
                Card("야츠하", "http://furuyonideck.com/images/bi/32/3.png", "여덟잎야츠하거울의저편", 11, true),
                Card("하츠미", "http://furuyonideck.com/images/ge/33/0.png", "수뢰구", 1, false),
                Card("하츠미", "http://furuyonideck.com/images/ge/33/1.png", "수류", 2, false),
                Card("하츠미", "http://furuyonideck.com/images/ge/33/2.png", "강산", 3, false),
                Card("하츠미", "http://furuyonideck.com/images/ge/33/3.png", "해일", 4, false),
                Card("하츠미", "http://furuyonideck.com/images/ge/33/4.png", "준비만전", 5, false),
                Card("하츠미", "http://furuyonideck.com/images/ge/33/5.png", "나침반", 6, false),
                Card("하츠미", "http://furuyonideck.com/images/ge/33/6.png", "파도부르기", 7, false),
                Card("하츠미", "http://furuyonideck.com/images/bi/33/0.png", "이사나해역", 8, true),
                Card("하츠미", "http://furuyonideck.com/images/bi/33/1.png", "오요기비포화", 9, true),
                Card("하츠미", "http://furuyonideck.com/images/bi/33/2.png", "카라하리등대", 10, true),
                Card("하츠미", "http://furuyonideck.com/images/bi/33/3.png", "미오비키항로", 11, true),
                Card("미즈키", "http://furuyonideck.com/images/ge/34/0.png", "진두", 1, false),
                Card("미즈키", "http://furuyonideck.com/images/ge/34/1.png", "반공", 2, false),
                Card("미즈키", "http://furuyonideck.com/images/ge/34/2.png", "쏘아떨구기", 3, false),
                Card("미즈키", "http://furuyonideck.com/images/ge/34/3.png", "호령", 4, false),
                Card("미즈키", "http://furuyonideck.com/images/ge/34/4.png", "방벽", 5, false),
                Card("미즈키", "http://furuyonideck.com/images/ge/34/5.png", "제압전진", 6, false),
                Card("미즈키", "http://furuyonideck.com/images/ge/34/6.png", "전장", 7, false),
                Card("미즈키", "http://furuyonideck.com/images/bi/34/0.png", "하치류천주각", 8, true),
                Card("미즈키", "http://furuyonideck.com/images/bi/34/1.png", "히자마루삼중루", 9, true),
                Card("미즈키", "http://furuyonideck.com/images/bi/34/2.png", "타테나시대수문", 10, true),
                Card("미즈키", "http://furuyonideck.com/images/bi/34/3.png", "야마시로미즈키의전투의함성", 11, true),
                Card("메구미", "http://furuyonideck.com/images/ge/35/0.png", "공섬", 1, false),
                Card("메구미", "http://furuyonideck.com/images/ge/35/1.png", "타척", 2, false),
                Card("메구미", "http://furuyonideck.com/images/ge/35/2.png", "껍질치기", 3, false),
                Card("메구미", "http://furuyonideck.com/images/ge/35/3.png", "장대찌르기", 4, false),
                Card("메구미", "http://furuyonideck.com/images/ge/35/4.png", "갈대", 5, false),
                Card("메구미", "http://furuyonideck.com/images/ge/35/5.png", "봉선화", 6, false),
                Card("메구미", "http://furuyonideck.com/images/ge/35/6.png", "찔레꽃", 7, false),
                Card("메구미", "http://furuyonideck.com/images/bi/35/0.png", "인과율의뿌리", 8, true),
                Card("메구미", "http://furuyonideck.com/images/bi/35/1.png", "가능성의가지", 9, true),
                Card("메구미", "http://furuyonideck.com/images/bi/35/2.png", "결말의과실", 10, true),
                Card("메구미", "http://furuyonideck.com/images/bi/35/3.png", "타키가와메구미의손바닥", 11, true),
                Card("카나에", "http://furuyonideck.com/images/ge/36/0.png", "공상", 1, false),
                Card("카나에", "http://furuyonideck.com/images/ge/36/1.png", "각본화", 2, false),
                Card("카나에", "http://furuyonideck.com/images/ge/36/2.png", "연출화", 3, false),
                Card("카나에", "http://furuyonideck.com/images/ge/36/3.png", "단행", 4, false),
                Card("카나에", "http://furuyonideck.com/images/ge/36/4.png", "잔광", 5, false),
                Card("카나에", "http://furuyonideck.com/images/ge/36/5.png", "즉흥", 6, false),
                Card("카나에", "http://furuyonideck.com/images/ge/36/6.png", "봉살", 7, false),
                Card("카나에", "http://furuyonideck.com/images/bi/36/0.png", "어렴풋한이야기", 8, true),
                Card("카나에", "http://furuyonideck.com/images/bi/36/1.png", "무수한별빛", 9, true),
                Card("카나에", "http://furuyonideck.com/images/bi/36/2.png", "이밤을굽이굽이펴리라", 10, true),
                Card("카나에", "http://furuyonideck.com/images/bi/36/3.png", "겨레의머나먼하늘", 11, true),
                Card("쿠루루A2", "http://furuyonideck.com/images/ge/37/0.png", "블래스터", 1, false),
                Card("쿠루루A2", "http://furuyonideck.com/images/ge/37/1.png", "레일건", 2, false),
                Card("쿠루루A2", "http://furuyonideck.com/images/ge/37/2.png", "쿠루룽", 3, false),
                Card("쿠루루A2", "http://furuyonideck.com/images/ge/37/3.png", "토네이도", 4, false),
                Card("쿠루루A2", "http://furuyonideck.com/images/ge/37/4.png", "리게이너", 5, false),
                Card("쿠루루A2", "http://furuyonideck.com/images/ge/37/5.png", "모듀르", 6, false),
                Card("쿠루루A2", "http://furuyonideck.com/images/ge/37/6.png", "리플렉터", 7, false),
                Card("쿠루루A2", "http://furuyonideck.com/images/bi/37/0.png", "드레인데빌", 8, true),
                Card("쿠루루A2", "http://furuyonideck.com/images/bi/37/1.png", "빅골렘", 9, true),
                Card("쿠루루A2", "http://furuyonideck.com/images/bi/37/2.png", "인더스트리아", 10, true),
                Card("쿠루루A2", "http://furuyonideck.com/images/bi/37/3.png", "커넥트다이브", 11, true),
                Card("하츠미A", "http://furuyonideck.com/images/ge/38/0.png", "수뢰구", 1, false),
                Card("하츠미A", "http://furuyonideck.com/images/ge/38/1.png", "수류", 2, false),
                Card("하츠미A", "http://furuyonideck.com/images/ge/38/2.png", "강산", 3, false),
                Card("하츠미A", "http://furuyonideck.com/images/ge/38/3.png", "잠뢰", 4, false),
                Card("하츠미A", "http://furuyonideck.com/images/ge/38/4.png", "준비만전", 5, false),
                Card("하츠미A", "http://furuyonideck.com/images/ge/38/5.png", "나침반", 6, false),
                Card("하츠미A", "http://furuyonideck.com/images/ge/38/6.png", "파도부르기", 7, false),
                Card("하츠미A", "http://furuyonideck.com/images/bi/38/0.png", "사기리해역", 8, true),
                Card("하츠미A", "http://furuyonideck.com/images/bi/38/1.png", "오요기비포화", 9, true),
                Card("하츠미A", "http://furuyonideck.com/images/bi/38/2.png", "카라하리등대", 10, true),
                Card("하츠미A", "http://furuyonideck.com/images/bi/38/3.png", "와다나가항로", 11, true),
                Card("야츠하A", "http://furuyonideck.com/images/ge/39/0.png", "별의손톱", 1, false),
                Card("야츠하A", "http://furuyonideck.com/images/ge/39/1.png", "어둠의아가리", 2, false),
                Card("야츠하A", "http://furuyonideck.com/images/ge/39/2.png", "거울의악마", 3, false),
                Card("야츠하A", "http://furuyonideck.com/images/ge/39/3.png", "환영보법", 4, false),
                Card("야츠하A", "http://furuyonideck.com/images/ge/39/4.png", "의지", 5, false),
                Card("야츠하A", "http://furuyonideck.com/images/ge/39/5.png", "계약", 6, false),
                Card("야츠하A", "http://furuyonideck.com/images/ge/39/6.png", "들러붙는꽃", 7, false),
                Card("야츠하A", "http://furuyonideck.com/images/bi/39/0.png", "여덟잎거울의허무한벚꽃", 8, true),
                Card("야츠하A", "http://furuyonideck.com/images/bi/39/1.png", "여덟잎거울의허무한벚꽃", 9, true),
                Card("야츠하A", "http://furuyonideck.com/images/bi/39/2.png", "여덟잎거울의허무한벚꽃", 10, true),
                Card("야츠하A", "http://furuyonideck.com/images/bi/39/3.png", "여덟잎거울의허무한벚꽃", 11, true),
                Card("카무이", "http://furuyonideck.com/images/ge/40/0.png", "붉은칼날", 1, false),
                Card("카무이", "http://furuyonideck.com/images/ge/40/1.png", "흩날리는칼날", 2, false),
                Card("카무이", "http://furuyonideck.com/images/ge/40/2.png", "사검난인", 3, false),
                Card("카무이", "http://furuyonideck.com/images/ge/40/3.png", "베어내기", 4, false),
                Card("카무이", "http://furuyonideck.com/images/ge/40/4.png", "가시꿰기", 5, false),
                Card("카무이", "http://furuyonideck.com/images/ge/40/5.png", "혈정난류", 6, false),
                Card("카무이", "http://furuyonideck.com/images/ge/40/6.png", "피보라", 7, false),
                Card("카무이", "http://furuyonideck.com/images/bi/40/0.png", "등불", 8, true),
                Card("카무이", "http://furuyonideck.com/images/bi/40/1.png", "묘도", 9, true),
                Card("카무이", "http://furuyonideck.com/images/bi/40/2.png", "신위", 10, true),
                Card("카무이", "http://furuyonideck.com/images/bi/40/3.png", "이치", 11, true),
                Card("렌리", "http://furuyonideck.com/images/ge/41/0.png", "거짓찌르기", 1, false),
                Card("렌리", "http://furuyonideck.com/images/ge/41/1.png", "임시변통", 2, false),
                Card("렌리", "http://furuyonideck.com/images/ge/41/2.png", "누명씌우기", 3, false),
                Card("렌리", "http://furuyonideck.com/images/ge/41/3.png", "약올리는몸짓", 4, false),
                Card("렌리", "http://furuyonideck.com/images/ge/41/4.png", "뜬구름잡기", 5, false),
                Card("렌리", "http://furuyonideck.com/images/ge/41/5.png", "낚시질", 6, false),
                Card("렌리", "http://furuyonideck.com/images/ge/41/6.png", "끌어속이기", 7, false),
                Card("렌리", "http://furuyonideck.com/images/bi/41/0.png", "요러하리라라", 8, true),
                Card("렌리", "http://furuyonideck.com/images/bi/41/1.png", "너르로로리러", 9, true),
                Card("렌리", "http://furuyonideck.com/images/bi/41/2.png", "내라라려루레", 10, true),
                Card("렌리", "http://furuyonideck.com/images/bi/41/3.png", "렌리의영락한말로", 11, true),

                )
            db.cardDao().insertAll(*test)
        }
    }

    Toast.makeText(context, "데이터 저장이 완료되었습니다", Toast.LENGTH_SHORT).show()

}
